config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :bank_accounts
  
  resources :clients do
    resources :bank_accounts, controller: "clients/bank_accounts", except: [:index, :show, :destroy]
  end

  namespace :api do
    namespace :v1 do
       post 'bank_accounts/new_transaction', to: 'bank_accounts#transaction'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client

  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  before_validation :default_balance

  has_many :transactions

  def default_balance
    if self.new_record?
      self.balance = 0.00
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :client_number, presence: true, uniqueness: true

    has_many :bank_accounts

    before_save :format_client_name

    def format_client_name
        self.first_name = self.first_name.upcase
        self.last_name = self.last_name.upcase
    end

    def to_s
        "#{last_name}, #{first_name}"
    end

    def number_of_accounts
        self.bank_accounts.count
    end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :bank_account

  TYPES = ['withdraw', 'deposit']

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_number, presence: true, uniqueness: true
  validates :transaction_type, presence: true, inclusion: { in: TYPES }

  before_validation :uniq_transaction_number

  def uniq_transaction_number
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
    module V1
        class BankAccountsController < ApplicationController
            def transaction
                amount = params[:amount]
                transaction_type = params[:transaction_type]
                bank_account_id = params[:bank_account_id]

                errors = ::BankAccounts::ValidateTransaction.new(
                    amount: amount,
                    transaction_type: transaction_type,
                    bank_account_id: bank_account_id
                ).execute!

                if errors.size > 0
                    render json: { errors: errors }, status: 402
                else
                    bank_account = ::BankAccounts::PerformTransaction.new(
                        amount: amount,
                        transaction_type: transaction_type,
                        bank_account_id: bank_account_id
                    ).execute!

                    render json: { balance: bank_account.balance }
                end
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController

    before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

    def index
        @bank_accounts = BankAccount.all
    end

    def new
        @bank_account = BankAccount.new
    end

    def create
        @bank_account = BankAccount.new(bank_account_params)

        if @bank_account.save
            redirect_to bank_account_path(@bank_account.id)
        else
            render "new"
        end
    end

    def edit
    end

    def update
        if @bank_account.update(bank_account_params)
            redirect_to bank_account_path(@bank_account.id)
        else
            render "edit"
        end
    end

    def show
    end

    def destroy
        client = @bank_account.client
        if @bank_account.balance > 0
            redirect_to bank_account_path(@bank_account.id)
        else
            @bank_account.destroy!
            redirect_to client_path(client)
        end
    end
    
    private

    def set_bank_account
        @bank_account = BankAccount.find(params[:id])
    end

    def bank_account_params
        params.require(:bank_account).permit(:account_number, :client_id)
    end
end

app/controllers/clients/bank_accounts_controller.rb
module Clients
    class BankAccountsController < ApplicationController
        before_action :load_parent_object
        before_action :load_object, only: [:edit, :update]

        def new
            @bank_account = BankAccount.new
        end

        def create
            @bank_account = BankAccount.new(bank_account_params)
            @bank_account.client = @client

            if @bank_account.save
                redirect_to bank_account_path(@bank_account.id)
            else
                render "new"
            end
        end

        def edit
        end

        def update
            @bank_account.client = @client

            if @bank_account.update(bank_account_params)
                redirect_to bank_account_path(@bank_account.id)
            else
                render "edit"
            end
        end
        
        private
        def load_object
            @bank_account = BankAccount.find(params[:id])
        end

        def load_parent_object
            @client = Client.find(params[:client_id])
        end

        def bank_account_params
            params.require(:bank_account).permit(:account_number)
        end
    end
end

app/controllers/clients_controller.rb
class ClientsController < ActionController::Base
    before_action :set_client, only: [:show, :edit, :update, :destroy]

    def index
        @clients = Client.all
    end
    def new
        @client = Client.new
    end

    def create
        @client = Client.new(client_params)

        if @client.save
            redirect_to client_path(@client.id)
        else
            render "new"
        end
    end

    def edit
    end
    
    def update
        if @client.update(client_params)
            redirect_to client_path(@client.id)
        else
            render "edit"
        end
    end

    def show
    end

    def destroy 
        @client.destroy!
        redirect_to clients_path
    end

   private

    def set_client
        @client = Client.find(params[:id])
    end

    def client_params
        params.require(:client).permit(:client_number, :first_name, :last_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def number_of_clients
        Client.count
    end
end

app/views/bank_accounts/_form.html.haml
= simple_form_for bank_account, html: { class: 'form-horizontal' } do |f|
    = f.association :client, input_html: { class: "form-control" }, prompt: "Select an existing Client", label: false
    = f.input :account_number, input_html: { class: "form-control" }, label: false, placeholder: "Set Account Number"
    %hr
    .form-actions
        = f.submit class: "btn btn-success" do
            Save Bank Account
        = link_to root_path, class: "btn btn-default" do
            Cancel

app/views/bank_accounts/_transactions.html.haml
%table.table.table-hover
    %thead
        %tr
            %th Date of Transaction
            %th Transaction Type
            %th Amount
    %tbody
        -@bank_account.transactions.each do |transaction|
            %tr
                %td #{transaction.created_at}
                %td #{transaction.transaction_type}
                %td #{number_to_currency(transaction.amount, presicion: 2, unit: '$')}
        %tr
            %th
            %th Balance
            %th #{number_to_currency(@bank_account.balance, presicion: 2, unit: '$')}

app/views/bank_accounts/edit.html.haml
%h1
  Edit Bank Account
  %small
    #{@bank_account.account_number}
  
= render partial: "form", locals: { bank_account: @bank_account }

app/views/bank_accounts/index.html.haml
%h1
    Bank Accounts

= link_to new_bank_account_path, class: "btn btn-success" do 
    New Bank Account

%table.table.table-hover
    %thead
        %tr
            %th Account Number
            %th Client
            %th Balance
            %th Acctions
    %tbody
        - @bank_accounts.each do |bank_account|
            %tr
                %td #{bank_account.account_number}
                %td
                    = link_to client_path(bank_account.id) do
                        #{bank_account.client}
                %td #{number_to_currency(bank_account.balance, precision: 2, unit: '$')}
                %td 
                    = link_to bank_account_path(bank_account.id), class: "btn btn-info" do
                        Show

app/views/bank_accounts/new.html.haml
%h1
    Create a New Bank Account

= render partial: "form", locals: { bank_account: @bank_account }

app/views/bank_accounts/show.html.haml
%h2
    Account Number: #{@bank_account.account_number}

%p
    by #{@bank_account.client}

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-success" do
    New Transaction

= link_to client_path(@bank_account.client.id), class: "btn btn-default" do
    Back to #{@bank_account.client}

= render partial: "transactions", locals: { bank_account: @bank_account }

= link_to edit_bank_account_path(@bank_account.id), class: "btn btn-info" do 
    Edit Bank Account

= link_to bank_account_path(@bank_account.id), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure to delete this account?' } do
    Delete Account

#parameters{ data: { bank_account_id: @bank_account.id } }

#modal-transaction.modal.fade.modal-fade
    .modal-dialog
        .modal-content
            .modal-header
                %button.close{type:'button', data:{dismiss:'modal'}}
                    %span{aria:{hidden:'true'}}
                        %i.fa.fa-close
                    %span.sr-only Close
                %h4.modal-title
                    New Transaction
            .modal-body
                .row
                    .col-md-12
                        .notification
                .row
                    .col-md-6
                        %label
                            Amount
                        = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
                    .col-md-6
                        %label 
                            Transaction Type
                        = select_tag :transaction_type, options_for_select(Transaction::TYPES), id: "select-types", class: "form-control"
            .modal-footer
                %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
                %button#btn-save.btn.btn-success{type:'button'} Save



= javascript_include_tag 'bank_accounts/show'
:javascript
    $(document).ready(function(){
        show.init();
    });

app/views/clients/_bank_accounts.html.haml
%table.table.table-hover
    %thead
        %tr
            %th Account Number
            %th Balance
            %th Actions
    %tbody
        - bank_accounts.each do |bank_account|
            %tr
                %td #{bank_account.account_number}
                %td #{number_to_currency(bank_account.balance, unit: "$", presicion: 2)}
                %td
                    = link_to bank_account_path(bank_account.id), class: "btn btn-info" do
                        Show

app/views/clients/_form.html.haml
= simple_form_for client do |f|
    = f.input :client_number, input_html: { class: "form-control" }, label: false, placeholder: "Client Number"
    = f.input :first_name, input_html: { class: "form-control" }, label: false, placeholder: "First Name"
    = f.input :last_name, input_html: { class: "form-control" }, label: false, placeholder: "Last Name"
    %hr
    .form-actions
        = f.submit class: "btn btn-success" do
            Save New Client
        = link_to root_path, class: "btn btn-default" do
            Cancel

app/views/clients/_table.html.haml
%table.table.table-hover
    %thead
        %tr
            %th Client Number
            %th Name
            %th Number of Accounts
            %th Actions
    %tbody
        - clients.each do |c|
            %tr
                %td #{c.client_number}
                %td #{c}
                %td #{c.number_of_accounts}
                %td
                    = link_to client_path(c.id), class: "btn btn-primary" do
                        Show

app/views/clients/bank_accounts/_form.html.haml
= simple_form_for [client, bank_account] do |f|
    = f.input :account_number, input_html: { class: "form-control" }, label: false, placeholder: "Account Number"
    .form-actions
        = f.submit class: "btn btn-primary" do
            Save Bank Account
        = link_to client_path(client.id), class: "btn btn-primary" do
            Cancel

app/views/clients/bank_accounts/edit.html.haml
%h1
    Edit Bank Account for #{@client}

= render partial: "form", locals: { client: @client, bank_account: @bank_account }

app/views/clients/bank_accounts/new.html.haml
%h1 
    New Bank Account for #{@client}

= render partial: "form", locals: { client: @client, bank_account: @bank_account }

app/views/clients/edit.html.haml
%h1
    Edit Client

= render partial: "form", locals: { client: @client }

app/views/clients/index.html.haml
%link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
%h1
    Clients
 
= render partial: "table", locals: { clients: @clients }

app/views/clients/new.html.haml
%link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
%h1
    New Client

= render partial: "form", locals: { client: @client }

app/views/clients/show.html.haml
%link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/

%h2
    Client Name: #{@client}
    
%p
    Client Number: 
    %b #{@client.client_number}

= link_to edit_client_path(@client), class: "btn btn-info" do
    Edit Client

= link_to new_client_bank_account_path(@client.id), class: "btn btn-primary" do
    New Bank Account
 
= render partial: "bank_accounts", locals: { bank_accounts: @client.bank_accounts }

app/views/home/index.html.haml
.jumbotron
    .container
        %h2
            Hugo's Bank

            .row
                .col-md-12
                    %p
                        We have 
                        %b #{number_of_clients} 
                        Clients registered

            .row
                .col-md-12
                    .col-md-6
                        = link_to new_bank_account_path, html_options = {class: "btn btn-info btn-lg"} do
                            Create Bank Account
                    .col-md-6
                        = link_to new_client_path, html_options = {class: "btn btn-info btn-lg"} do
                            Create Client

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hugo's Bank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            Home
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/clients">View Clients</a></li>
            <li><a href="/bank_accounts">View Bank Accounts</a></li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>